"""Add telemetry columns

Revision ID: 7572cbe79eb5
Revises: a4ed36d8c596
Create Date: 2026-09-23 01:46:08.818727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7572cbe79eb5'
down_revision: Union[str, Sequence[str], None] = 'a4ed36d8c596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('worker_bpm', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('fatigue_index', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('vibration_rms', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('acceleration_z', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('gas_co_ppm', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('dust_density_mg_m3', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('ambient_light_lux', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'ambient_light_lux')
    op.drop_column('interactions', 'dust_density_mg_m3')
    op.drop_column('interactions', 'gas_co_ppm')
    op.drop_column('interactions', 'acceleration_z')
    op.drop_column('interactions', 'vibration_rms')
    op.drop_column('interactions', 'fatigue_index')
    op.drop_column('interactions', 'worker_bpm')
    # ### end Alembic commands ###
